### ISSUE TITLE
Feature request: Log to file and console

### ISSUE THREAD

**Issue by aSemy** [conorcunningham/google-ddns#12]
When running in Docker, there's no logging displayed. That's because the logger is only set to log to a file. 

A quick fix is to log to both console and file. If necessary, 'log to file or console or both' could be configurable?

**Comment by aSemy** [comment]
I'm no Python expert so the PR is a proposal, please check it over to make sure it's good :)

**Comment by conorcunningham** [comment]
Thank you for the help and contributions. The logging works a treat and is a nice improvement. Again, cheers!

**Comment by aSemy** [comment]
My pleasure! I'm happy to help, and my thanks go to you for making such a useful project. 

Here's a really minor thing to fix, there's a spelling mistake (dynmaic > dynamic) in the project tag  :) https://github.com/topics/python-dynmaic-dns

**Comment by conorcunningham** [comment]
Nice catch. I've updated the spelling in the tag. Cheers!
